# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Netlify Boilerplate
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "" # the subpath of your site if applicable, e.g. /blog
url: "https://jekyll-netlify-boilerplate.netlify.com" # the base hostname & protocol for your site, e.g. https://example.com


# Enable section IDs in frontmatter, useful for identifying current page
# (used as a hook for styling etc)
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: true

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false


# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

plugins:
 - 'jekyll-seo-tag'

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://docs.jekyll.plus"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           Pete Seth
    title:          Lead Developer  
    avatar:         avatar-tom.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    john:
      name:         John Brown
      title:        Support     
      avatar:       avatar-john.png
    evan:
      name:         Evan Wells
      title:        Support    
      avatar:       avatar-evan.png
    sara:
      name:         Sara Galen
      title:        Lead Developer     
      avatar:       avatar-sara.png
    alex:
      name:         Alex Koch
      title:        Design Engineer     
      avatar:       avatar-alex.png
    daniel:
      name:         Daniel Shultz
      title:        Developer      
      avatar:       avatar-daniel.png
    tom:
      name:         Tom Farrell
      title:        Developer     
      avatar:       avatar-tom.png

# Social icons displayed in footer
social:
    email:
    website:
    facebook:       https://www.facebook.com/
    flickr:
    dribbble:
    github:
    googleplus:
    instagram:      https://www.instagram.com/
    linkedin:
    pinterest:
    twitter:        https://twitter.com/
    vimeo:          https://vimeo.com/
    youtube:

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      Made by a <a href="https://ivanchromjak.com/">human</a> somewhere on the planet earth.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc